script: bundle exec rake
bundler_args: --without bin docs
branches:
  only:
  - master
rvm:
- 1.9.3
- 2.0.0
- jruby
env:
  - OX=1 OJ=1
  - NOKOGIRI=1
gemfile:
  - Gemfile
matrix:
  exclude:
    - rvm: jruby
      env: OX=1 OJ=1
      gemfile: Gemfile
